require "config"
require "libs.functions"

require "prototypes.emptyItem"
require "prototypes.miningRoboport"
require "prototypes.miningRobot"
require "prototypes.robotMiningSite"
require "prototypes.robotMiningSite-large"
require "prototypes.robotMiningSite-old"
require "prototypes.invisibleStorageChest"
require "prototypes.logisticDeciderCombinator"
require "prototypes.miningRobotSpeedTechnology"
require "prototypes.technology"